### ISSUE TITLE
No run configurations available

### ISSUE THREAD

**Issue by laurentkempe** [JetBrains/resharper-rider-plugin#10]
Opening the solution created with 0.7.0 in Rider 2018.3.3, no run configurations are available!

![image](https://user-images.githubusercontent.com/272612/52817673-d18d9f00-30a4-11e9-9dc0-60ad057ea7a1.png)

**Comment by matkoch** [comment]
Can't reproduce. If you call `dotnet new resharper-rider-plugin --name test`, could you check then if there is an `.idea` folder?

**Comment by laurentkempe** [comment]
I created one with `dotnet new resharper-rider-plugin --name MyAwesomePlugin` and can not see the run configuration in Rider 2018.3.3
I have the .idea folder with the following content

    > ls -r .idea
    
    
        Directory: C:\Users\laure\projects\Resharper\MyAwesomePlugin\.idea
    
    
    Mode                LastWriteTime         Length Name
    ----                -------------         ------ ----
    d-----        2/28/2019   7:28 PM                .idea.MyAwesomePlugin
    
    
        Directory: C:\Users\laure\projects\Resharper\MyAwesomePlugin\.idea\.idea.MyAwesomePlugin
    
    
    Mode                LastWriteTime         Length Name
    ----                -------------         ------ ----
    d-----        2/28/2019   7:28 PM                .idea
    
    
        Directory: C:\Users\laure\projects\Resharper\MyAwesomePlugin\.idea\.idea.MyAwesomePlugin\.idea
    
    
    Mode                LastWriteTime         Length Name
    ----                -------------         ------ ----
    d-----        2/28/2019   7:28 PM                runConfigurations
    
    
        Directory: C:\Users\laure\projects\Resharper\MyAwesomePlugin\.idea\.idea.MyAwesomePlugin\.idea\runConfigurations
    
    
    Mode                LastWriteTime         Length Name
    ----                -------------         ------ ----
    -a----        2/28/2019   7:28 PM            569 rdgen__Unix_.xml
    -a----        2/28/2019   7:28 PM            597 rdgen__Windows_.xml
    -a----        2/28/2019   7:28 PM            558 Rider__Unix_.xml
    -a----        2/28/2019   7:28 PM            575 Rider__Windows_.xml
    -a----        2/28/2019   7:28 PM            635 VisualStudio.xml

**Comment by laurentkempe** [comment]
This is fixed also now
![image](https://user-images.githubusercontent.com/272612/55033453-85bf0580-5013-11e9-91f5-6045b6455503.png)
Maybe in version 0.9.0 or could it be because I installed BashSupport plugin!
