### ISSUE TITLE
Fail to resolve maven-metadata

### ISSUE THREAD

**Issue by farnyser** [JetBrains/resharper-rider-plugin#17]
Hi guys, 

I can't run the sample plugin for rider. 
There seems to be a problem with the current gradle.build script.

`gradlew.bat :runIde`

> FAILURE: Build failed with an exception.
>
> * What went wrong:
> A problem occurred configuring root project 'myproject'.
>
> Could not resolve all files for configuration ':detachedConfiguration1'.
   > Could not resolve com.jetbrains.intellij.rider:riderRD:2018.3-SNAPSHOT.
     Required by:
         project :
      > Could not resolve com.jetbrains.intellij.rider:riderRD:2018.3-SNAPSHOT.
         > Unable to load Maven meta-data from https://repo.labs.intellij.net/central-proxy/com/jetbrains/intellij/rider/riderRD/2018.3-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://repo.labs.intellij.net/central-proxy/com/jetbrains/intellij/rider/riderRD/2018.3-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://repo.labs.intellij.net/central-proxy/com/jetbrains/intellij/rider/riderRD/2018.3-SNAPSHOT/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

I tried changing the version to 2019.1 with no luck

**Comment by yuzd** [comment]
how to change the version to 2019.1

**Comment by matkoch** [comment]
Issue should be resolved with 0.11.0
