### ISSUE TITLE
Missing "vswhere" when running "VisualStudio" target

### ISSUE THREAD

**Issue by Wortex17** [JetBrains/resharper-rider-plugin#22]
In commit 4b3536aa8167c492e7ed514929ab338f882358b0 vswhere.exe was removed.
But running the "VisualStudio" target fail because the powerShell script is not able to find it.
Specifically, [settings.ps1:6](https://github.com/JetBrains/resharper-rider-plugin/blob/5b39e9903d2c9a0d3272e723a7853137dbf5d953/content/settings.ps1#L6) invokes it.

**Comment by matkoch** [comment]
Will be fixed as part of next release
