### ISSUE TITLE
 Unsupported class file major version 60

### ISSUE THREAD

**Issue by sstcvetkov** [JetBrains/resharper-rider-plugin#36]
Hello,

Can't run `Generate protocol (Windows)` or `Rider (Windows)`, got this error.
Tried to use jdk 13-15.

`C:\Windows\System32\cmd.exe /c gradlew.bat :rdgen
Starting a Gradle Daemon, 2 incompatible and 1 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.
* Where:
Settings file 'C:\Users\sergeyt\src\wms\MyAwesomePlugin1\settings.gradle'
* What went wrong:
Could not compile settings file 'C:\Users\sergeyt\src\wms\MyAwesomePlugin1\settings.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 60
  java.lang.IllegalArgumentException: Unsupported class file major version 60
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
...`

  1 error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full i
nsights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s

Process finished with exit code 1.

`

**Comment by ForNeVeR** [comment]
> Tried to use jdk 13-15.

Your problem is likely related to this. Please use JDK 11 (since Rider right now depends on it; we have plans to upgrade later, but not right now).
