### ISSUE TITLE
About a debugger plug-in for a Rider getting breakpoints

### ISSUE THREAD

**Issue by yyh9488** [JetBrains/resharper-rider-plugin#37]
To make a debugger plug-in for Rider, I have looked up a lot of information but do not know where to get the data of breakpoints, such as the location of breakpoints. Now know the access method is to use the Kotlin com. Jetbrains. Rider. Test. ScriptingApi. ToggleBreakpoint access breakpoints to c #. Want to know that the Rider API can get breakpoint data directly

**Comment by ArsenyChernyaev** [comment]
Hey, you can use XBreakpointManager in order to access breakpoints data. You can obtain instance of this component by calling XDebuggerManager.getInstance(project).breakpointsManager. The only thing you need is a reference to a Project.

**Comment by yyh9488** [comment]
Need to use Kotlin to pass to Rider?

**Comment by ArsenyChernyaev** [comment]
Yes, like this. You can use Java if you want to.

**Comment by yyh9488** [comment]
I originally wanted to use rider to get breakpoint data, but now it seems unrealistic
