### ISSUE TITLE
Latest package (2021.1.0) fails to run example plugin

### ISSUE THREAD

**Issue by gibertoni** [JetBrains/resharper-rider-plugin#38]
Although the master branch is correctly configured and specifies a gradle distribution that works:
`distributionUrl=https\://cache-redirector.jetbrains.com/services.gradle.org/distributions/gradle-7.1-all.zip`

The example plugin installed using 2021.1.0 release specifies:
`distributionUrl=https\://cache-redirector.jetbrains.com/services.gradle.org/distributions/gradle-6.8.3-all.zip`

The commit to fix this gradle version was made recently: c4fa5f1a8eaeffef600e2321ed82d41d130033c6
The project should probably release a new version to ensure the default template works.

**Comment by matkoch** [comment]
So what was the error that was shown? Templates are only published when they actually work.

**Comment by gibertoni** [comment]
The error shown to me (Mac OS X 11 - Big Sur) was:
```
Downloading https://cache-redirector.jetbrains.com/services.gradle.org/distributions/gradle-6.8.3-all.zip
..............10%..............20%...............30%..............40%..............50%...............60%..............70%..............80%...............90%..............100%

Welcome to Gradle 6.8.3!

Here are the highlights of this release:
 - Faster Kotlin DSL script compilation
 - Vendor selection for Java toolchains
 - Convenient execution of tasks in composite builds
 - Consistent dependency resolution

For more details see https://docs.gradle.org/6.8.3/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/guilherme.gibertoni/Documents/Projects/RiderPlugins/PrefabInspectionPlugin/settings.gradle'

* What went wrong:
Could not compile settings file '/Users/guilherme.gibertoni/Documents/Projects/RiderPlugins/PrefabInspectionPlugin/settings.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 60
  
  java.lang.IllegalArgumentException: Unsupported class file major version 60
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)
        at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
        at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
        at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
        at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
        at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
...
```

The stack continues, but this top most part says enough.
Searching for this I understood that the IDE could not be run with this gradle version, and one thread on stackoverflow suggested that from 2021.1.x+ gradle version 7.x+ should be used.

I am not sure about the dependencies, but updating it worked perfectly.

**Comment by matkoch** [comment]
Does it work from command-line? Remember to stop gradle agents before.

**Comment by gibertoni** [comment]
The plugin was created using
`dotnet new resharper-rider-plugin --name PrefabInspectionPlugin --include-samples `

and then I tried to run the IDE through:
`gradlew :runIde`

And also tried through RIder itself using the included run configuration to run on Unix

**Comment by matkoch** [comment]
Hey @gibertoni! Could you try with the latest version?

**Comment by matkoch** [comment]
I'll close this issue, feel free to create a new one if you're still running into any problems.
