### ISSUE TITLE
Add a sample window

### ISSUE THREAD

**Issue by ArkTarusov** [JetBrains/resharper-rider-plugin#41]
Hello.
I spent a few days creating a window for the plugin, but I still couldn't do it.
for IDEA I could do it via `JBPopupFactory.getInstance().createComponentPopupBuilder()`.

It would be easier if this was already in example. There is such an example in old template, but it doesn't work either.
Is it possible to add an example here?
Is there any up-to-date documentation explaining how to create a rider plugin window?

**Comment by ForNeVeR** [comment]
Hi! It should work precisely the same as in IDEA (if we are talking about a Rider plugin). What doesn't work for you?

**Comment by ArkTarusov** [comment]
Strange, but today, after trying again to do the same as for IDEA, I got the result I needed. Although, before creating the problem, I made sure that the methods found on the internet, as well as just generating Kotlin code in the same way as for the IDEA plugin, throws an exception indicating the action opening window, but without additional information.

I do not know why. But thanks for confirming that everything should work.)

It remains to understand how to display the result of cs-code in this window.

**Comment by ForNeVeR** [comment]
Next time you encounter such an error, please share the exception message and the stack trace; it would help us to diagnose the root issue.

I'm glad to hear the issue is resolved, anyway.

> It remains to understand how to display the result of cs-code in this window.

If I understand correctly, then you could use the Rd protocol to pass data from C# to Java side of the plugin, and then show it.
