### ISSUE TITLE
compileDotNet failed execution

### ISSUE THREAD

**Issue by Walrusking16** [JetBrains/resharper-rider-plugin#45]
When I try to to use :runIde it fails every time it tries to compile the plugin. I created the project files from the new solution screen in rider.

>Execution failed for task ':compileDotNet'.
> \> Process 'command 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe'' finished with non-zero exit value 1

When I have it show more info on the error it gives me the following.
> MSBUILD : error MSB1009: Project file does not exist.

This is the only file I have created in the plugin
![rider64_Y6Xx5bbwv5](https://user-images.githubusercontent.com/20746458/149573771-18c5ffe4-26d9-4075-a377-88b9dc9dae8a.png)

The build fails at line 72 of build.gradle
![idea64_Uw1L0RWAqu](https://user-images.githubusercontent.com/20746458/149573973-fffe6b00-c8c8-43a5-8a91-479d817b7e9f.png)

**Comment by matkoch** [comment]
Could you please try again with `dotnet new resharper-rider-plugin --name xxx` ? Creating from template in IDE is probably not going to work as of now.

**Comment by Walrusking16** [comment]
> Could you please try again with `dotnet new resharper-rider-plugin --name xxx` ? Creating from template in IDE is probably not going to work as of now.

Ya that seems to have fixed it, thanks for the help I have been stuck with that problem all night. I had trouble with the cli way last night but that seems to have resolved itself.

**Comment by matkoch** [comment]
Next time feel free to reach out immediately :)
