### ISSUE TITLE
Step publishPlugin throws HTTP 404

### ISSUE THREAD

**Issue by mu88** [JetBrains/resharper-rider-plugin#46]
Hey 👋🏻

I'm using your wonderful plugin template. When trying to publish the Rider plugin to the JetBrains NuGet feed, `nuget push` always returns `HTTP 404`. You can see this [here in my GitHub Action](https://github.com/vladyslav-burylov/resharper-testlinker2/runs/5766346291?check_suite_focus=true#step:9:1870).  
The funny thing is that the plugin's upload itself is successful. A couple of hours later, the new version appears in the JetBrains Marketplace ([see here](https://plugins.jetbrains.com/plugin/15518-test-linker-2/versions/stable/165318)).

So what's going wrong with `https://plugins.jetbrains.com`? Why does it always return `HTTP 404`?

Best regards
mu88

CC: @vladyslav-burylov

**Comment by matkoch** [comment]
Can you provide any information about when this started? I have some deployments from 30 days ago and they all look okay. Note that the first deployment must be done manually in all cases.

**Comment by mu88** [comment]
I cannot tell you, because it actually never worked 😁 in the beginning, @vladyslav-burylov did all releases by hand, uploading the assets to the JetBrains Marketplace manually. Then we've implemented the GitHub Action and use an API key to access JetBrains' NuGet feed. The API key seems to be correct, because otherwise the upload of the assets itself wouldn't work.

**Comment by matkoch** [comment]
Can you share some logs?

**Comment by mu88** [comment]
Uh, can't you access the logs of the GitHub Action (the very first link in the first post)? If so, sorry about the missing infos :)

Here are the last important lines of the log:
```
> Task :publishPlugin
Pushing ReSharperPlugin.TestLinker2.2021.3.4.nupkg to 'https://plugins.jetbrains.com'...
  PUT https://plugins.jetbrains.com/api/v2/package/
  NotFound https://plugins.jetbrains.com/api/v2/package/ 830ms
error: Response status code does not indicate success: 404 ().


Usage: dotnet nuget push [arguments] [options]

Arguments:
  [root]  Specify the path to the package and your API key to push the package to the server.

Options:
  -h|--help                      Show help information
  --force-english-output         Forces the application to run using an invariant, English-based culture.
  -s|--source <source>           Package source (URL, UNC/folder path or package source name) to use. Defaults to DefaultPushSource if specified in NuGet.Config.
  -ss|--symbol-source <source>   Symbol server URL to use.
  -t|--timeout <timeout>         Timeout for pushing to a server in seconds. Defaults to 300 seconds (5 minutes).
  -k|--api-key <apiKey>          The API key for the server.
  -sk|--symbol-api-key <apiKey>  The API key for the symbol server.
  -d|--disable-buffering         Disable buffering when pushing to an HTTP(S) server to decrease memory usage.
  -n|--no-symbols                If a symbols package exists, it will not be pushed to a symbols server.
  --no-service-endpoint          Does not append "api/v2/package" to the source URL.
  --interactive                  Allow the command to block and require manual action for operations like authentication.
  --skip-duplicate               If a package and version already exists, skip it and continue with the next package in the push, if any.

> Task :publishPlugin FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/runner/work/[resharper-testlinker2](https://github.com/vladyslav-burylov/resharper-testlinker2)/resharper-testlinker2/build.gradle' line: 196

* What went wrong:
Execution failed for task ':publishPlugin'.
> Process 'command 'dotnet'' finished with non-zero exit value 1
```

I've also attached the complete log.
[Release.yml.log](https://github.com/JetBrains/resharper-rider-plugin/files/8389023/Release.yml.log)

**Comment by matkoch** [comment]
Could you please ping me for the next release?

**Comment by mu88** [comment]
Sure 👍🏻

**Comment by mu88** [comment]
Same problem happened again for `2022.1.1`, please see the attached log file.

[Release.yml.log](https://github.com/JetBrains/resharper-rider-plugin/files/8596809/Release.yml.log)

**Comment by mu88** [comment]
Could you find some time to investigate the issue @matkoch?

**Comment by mu88** [comment]
Same problem happened again for `2022.1.2`

**Comment by mu88** [comment]
@matkoch Do you have any news about this? Rider 2022.2 is almost there and I'd really appreciate to get rid of this error with the next release of our Rider plugin

**Comment by matkoch** [comment]
> Note that the first deployment must be done manually in all cases.

It seems that the ReSharper plugin was never uploaded. What you've linked here is the Rider plugin.

**Comment by mu88** [comment]
@vladyslav-burylov Can you upload the ReSharper plugin, please?

**Comment by vladyslav-burylov** [comment]
Hi @mu88 - it looks like it was uploaded automatically, can you confirm?

> Version 2022.2.0 of the Test Linker 2 plugin has been approved by JetBrains and is now publicly available at the following link: https://plugins.jetbrains.com/plugin/15518-test-linker-2/versions/stable/203959.

Although release job still failing for some reason: https://github.com/vladyslav-burylov/resharper-testlinker2/actions/runs/2787498968

**Comment by mu88** [comment]
Hey @vladyslav-burylov 
If I understand @matkoch correctly, the ReSharper part of the plugin has to be uploaded manually once (that step is missing yet). Afterward, the automatic publishing will work.  
But at the moment, only the Rider part of the plugin will be uploaded automatically and that's why the build fails.

**Comment by vladyslav-burylov** [comment]
Right, I think it simple then: reshaper part is simply absent as far as I remember. Reshaper has similar (and better) plugin which does the same - TestCop

**Comment by mu88** [comment]
Okay, sounds good to me! Then we should skip the upload for the R# part.

@matkoch: is it possible to upload only the Rider but not the R# part of the plugin?

**Comment by matkoch** [comment]
Sure, just comment out this:

https://github.com/JetBrains/resharper-rider-plugin/blob/master/template/content/build.gradle#L207-L213

**Comment by mu88** [comment]
Ah, interesting! I thought the `nupkg` would contain both the R# and Rider plugin. If this is not the case, how is the Rider part uploaded?

**Comment by matkoch** [comment]
From the `publishPlugin` task. What you see in the Gradle file is just an extension.
