### ISSUE TITLE
outdated instructions of the template installation

### ISSUE THREAD

**Issue by shalom938** [JetBrains/resharper-rider-plugin#47]
the instructions are probably outdated. 
this works on linux with dotnet 6:
dotnet new --install  JetBrains.ReSharper.SamplePlugin.2021.2.1.nupkg

https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates#installing-a-template-package

**Comment by VirtualMaestro** [comment]
In addition to the previous message: for the latest release 2022 flag "--include-samples" is not valid anymore.

**Comment by lpnam0201** [comment]
> In addition to the previous message: for the latest release 2022 flag "--include-samples" is not valid anymore.

Apparently it was removed 11 days ago in https://github.com/JetBrains/resharper-rider-plugin/commit/7bd13636847546d1e5ba9798425bb3d7c0f1d0fe

**Comment by matkoch** [comment]
Samples are now part of the repository, and no longer of the template.

Installation command was updated. Thanks!
