### ISSUE TITLE
A problem occurred evaluating root project

### ISSUE THREAD

**Issue by VirtualMaestro** [JetBrains/resharper-rider-plugin#48]
Hello everyone,
I've just started to dig into plugin development for Rider. 
I've literally only downloaded the template and opened it with the IntelliJ Idea Community Edition version **2022.1**. 
Gradle failed with an exception:
"org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'myawesomeplugin'."
"Caused by: java.io.FileNotFoundException: C:\workspace\Work\Projects\PluginsDevelopment\Rider\MyAwesomePlugin\CHANGELOG.md (The system cannot find the file specified)"

Is this an issue with this template/Idea/some settings?
Or maybe this template isn't compatible with the latest Idea version (it just has been released recently)? 

Thank you for any hint!
![IdeaPluginGradleFail](https://user-images.githubusercontent.com/426870/163456671-f574b12d-8d4f-47eb-ae67-646977865765.png)

**Comment by matkoch** [comment]
I guess you've created from the template with the `--build-only` switch. This switch is only for updates to the infrastructure.
