### ISSUE TITLE
Fix/Improve the dependency to com.jetbrains.rdgen

### ISSUE THREAD

**Issue by Ironeer** [JetBrains/resharper-rider-plugin#49]
Hey guys,

I recently updated the build files of my plugin using your nuget package with `--build-only --force`. After that I had missing dependencies.
Luckily, Ivan Migalev, a member of your slack community, showed me a sample of how he included the new 2022.1 rdgen and it worked.

I suggest the change here because some other people might run into it. Also the new way uses the versioning in the style `2022.1` and not the confusing `0.221.xxx` versioning which improves the build.gradle.

Suggestion for the `build.gradle` file:
Remove this line:
```
plugins {
    id 'com.jetbrains.rdgen' version '0.212.307'  // remove this line
   // other plugins
}
 ```
In Favor of this:
```
buildscript {
    repositories {
        maven { setUrl("https://cache-redirector.jetbrains.com/maven-central") }
    }

    // https://search.maven.org/artifact/com.jetbrains.rd/rd-gen
    dependencies {
        classpath("com.jetbrains.rd:rd-gen:2022.1.3")
    }
}

plugins {
   // other plugins
}

apply {
    plugin("com.jetbrains.rdgen")
}
```

**Comment by matkoch** [comment]
Fixed in https://github.com/JetBrains/resharper-rider-plugin/commit/fc0101f51f347117a52fcac6ae434a4a0557e336
