### ISSUE TITLE
Notworking flags in command

### ISSUE THREAD

**Issue by JaroslawKAA** [JetBrains/resharper-rider-plugin#51]
In that command from getting started: dotnet new resharper-rider-plugin --name MyAwesomePlugin [--include-samples] [--resharper-only] [--build-only]
Don't work frags from square brackets.
<img width="575" alt="image" src="https://user-images.githubusercontent.com/57862416/167132390-fde16bbe-78b3-47a5-8024-670a599ad9c8.png">

**Comment by matkoch** [comment]
See https://github.com/JetBrains/resharper-rider-plugin/issues/47#issuecomment-1119747092
