### ISSUE TITLE
How to build and publish the plugin without jetbrains (Custom)

### ISSUE THREAD

**Issue by jamie-healey-xr** [JetBrains/resharper-rider-plugin#52]
I want to build the plugin and send it to people in our company - they can then install via "Add from disk"?

I can build from the ps1 script -- What's the actual build artefacts that can be installed?

Thanks

**Comment by matkoch** [comment]
I assume you want to install the Rider plugin since you mentioned "Installed from disk". The Rider artifacts are only build when using `gradlew.bat`. It should create a ZIP file in the output directory.

**Comment by jamie-healey-xr** [comment]
I got it thanks, I had to run gradlew.bat with `buildPlugin` task. My suggestion is to have a section on the readme about that.

Thanks again!
