### ISSUE TITLE
Plugin cannot be started locally

### ISSUE THREAD

**Issue by matkoch** [JetBrains/resharper-rider-plugin#57]
MacBook M1, EAP4 (but has been reported before)

(can't even copy the error message anymore)

<img width="1032" alt="Main-Start Failed-2022-10-17-SSZUEbU6@2x" src="https://user-images.githubusercontent.com/5005566/196261079-204ac911-313d-48bb-9cdb-fae75e850140.png">

**Comment by ForNeVeR** [comment]
Upgrade to gradle-intellij-plugin `1.10.0-SNAPSHOT` or wait for the release.

**Comment by matkoch** [comment]
Obsolete.
