### ISSUE TITLE
Could not resolve com.jetbrains.intellij.rider:riderRD:2022.2

### ISSUE THREAD

**Issue by foxjojo** [JetBrains/resharper-rider-plugin#58]
![企业微信截图_16667577851695](https://user-images.githubusercontent.com/35793308/197933204-0ff8ef48-a75a-4745-9923-a70564700e06.png)
I am try request https://www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/rider/riderRD/2022.2/riderRD-2022.2.pom 
![image](https://user-images.githubusercontent.com/35793308/197933467-cc34849b-de39-4e4c-bac6-26606b8bd216.png)

**Comment by foxjojo** [comment]
i find a methods to solve

**Comment by matkoch** [comment]
Could you clarify how you came up with this? It's not something that we know of.

**Comment by foxjojo** [comment]
maybe china network can't access this `https://www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/rider/riderRD/2022.2/riderRD-2022.2.pom`,so I find a same pom file in `mvnrepository.com`  ,and download it, copy the file download url and add this url to `build.gradle`, final it work

**Comment by ForNeVeR** [comment]
@foxjojo, does www.jetbrains.com works for you?
