### ISSUE TITLE
how to upgrade the plugin for rider 2022.3

### ISSUE THREAD

**Issue by Solidmatrix** [JetBrains/resharper-rider-plugin#60]
Got an error when installing plugin from disk:

Plugin 'xxx' (version '9999.0.0') is not compatible with the current version of the IDE, because it requires build 221.* or older but the current build is RD-223.7571.232

**Comment by ForNeVeR** [comment]
Currently, Rider 2022.3 SDK is broken, and will only be fixed after a bugfix release (see [RIDER-86051](https://youtrack.jetbrains.com/issue/RIDER-86051) for some details).

But you can try using the nightly SDK. Check commit 1d7044916da7d1082a5d4a9c4f7917ad5ad31eb2 on how to do that.

**Comment by matkoch** [comment]
Latest release also addresses this issue. @Solidmatrix let us know if you have any more problems.
