### ISSUE TITLE
Unable to install templates

### ISSUE THREAD

**Issue by LordDelacroix** [JetBrains/resharper-rider-plugin#63]
C:\>dotnet new install JetBrains.ReSharper.SamplePlugin.*.nupkg
The following template packages will be installed:
   JetBrains.ReSharper.SamplePlugin.*.nupkg

JetBrains.ReSharper.SamplePlugin.*.nupkg is not supported.

**Comment by matkoch** [comment]
@LordDelacroix I just tested the template on my Windows machine and (un)fortunately, everything is working.

Can you provide a couple more details? What .NET SDK are you using?

**Comment by LordDelacroix** [comment]
.NET 6 SDK - I've managed to get past this.

**Comment by matkoch** [comment]
Could you give more information how?
