### ISSUE TITLE
How to debug in Rider

### ISSUE THREAD

**Issue by xingchenxuup** [JetBrains/resharper-rider-plugin#64]

**Comment by ForNeVeR** [comment]
It depends on which part of Rider do you want to debug.

If you want to debug your plugin's frontend (JVM path), then just start the `runIde` Gradle task from IntelliJ IDEA in the **Debug** mode, and that's it.

If you want to debug your plugin's backend (.NET part), then:
- **works always**: start the `runIde` Gradle task (from either the command line or from the IntelliJ IDEA), and then **Attach** to the `Rider.Bakcend` process from Rider
- **may not work on certain platforms or Rider SDK versions**: there's a couple of so-called "self-debug configurations", "Rider (Windows)" and "Rider (Unix)" to start Rider from Rider. You can try starting them in debug mode.

**Comment by matkoch** [comment]
Closing, let us know if you need any further help!
