### ISSUE TITLE
Is must install visual studio?

### ISSUE THREAD

**Issue by JusamLiu** [JetBrains/resharper-rider-plugin#65]
![image](https://user-images.githubusercontent.com/19208568/216822719-b5b0649e-6c20-47d8-8f6e-da960011a857.png)
![image](https://user-images.githubusercontent.com/19208568/216822765-436d6350-cc75-4ecf-93b3-6e447b584e30.png)

when I run build plugin task,I got this error。 I found that run vswhere.exe first. I don't install the Visual studio.but I had install the rider.
how can I redirect the path to the rider's msbuild (..\JetBrains Rider\tools\MSBuild) or I must install the VS ?

**Comment by ForNeVeR** [comment]
I cannot for sure say about ReSharper plugin, but if you are only interested in Rider, then it's definitely possible without Visual Studio installed.

Take a look at [how's it organized in AvaloniaRider](https://github.com/ForNeVeR/AvaloniaRider/blob/7ce5baa666bd45029bc86db019aaf50f18aa42f4/build.gradle.kts#L156-L164).

**Comment by JusamLiu** [comment]
thanks, because I just use rider and unity. it's enough。 I found a way: 

change the code "if (isWindows)" to "if(false)"
or
change the getFileNames function first param to the rider's or dotnet's msbuild path

it works.

**Comment by matkoch** [comment]
@JusamLiu if you want you can test this fix: https://github.com/JetBrains/resharper-rider-plugin/commit/6687abe5e50cd8212a970806172e92ca7600ab8d

The reason we prefer the VisualStudio MSBuild is because minor parts of our plugin infrastructure (MSBuild tasks) only support that version.
