### ISSUE TITLE
Need a example for attach to process with SDK ?

### ISSUE THREAD

**Issue by chuongmep** [JetBrains/resharper-rider-plugin#79]
Hi team, can give a example how to use attach to process with SDK ? 
Thank you !
![image](https://github.com/JetBrains/resharper-rider-plugin/assets/31106432/9cd5186d-6f56-46bf-8738-d94a545aa5a4)

**Comment by ForNeVeR** [comment]
Check how Unity implements this.

The entry point is here: https://github.com/JetBrains/resharper-unity/blob/3f57a1b9ce1894573605e7af96cac09d24f44ef6/rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/actions/AttachToUnityProcessAction.kt

The attach workflow itself is here: https://github.com/JetBrains/resharper-unity/blob/3f57a1b9ce1894573605e7af96cac09d24f44ef6/rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/RunConfigurationUtil.kt
