### ISSUE TITLE
No build Configuration are generated

### ISSUE THREAD

**Issue by SlushUwU** [JetBrains/resharper-rider-plugin#82]
Hello, I just downloaded the https://github.com/jetbrains/resharper-rider-plugin template and everytime I want to create a new Project with the Template it generated everything but not the Build Configurations and I also have at ReSharperPlugin.<projectName>.Tests in the file TestEnvironment.cs on line 16 the following error:
![grafik](https://github.com/JetBrains/resharper-rider-plugin/assets/105487011/e586d5c9-4518-4ad0-8626-ae281d9b5d25)

Heres a Sample project I generated:
https://github.com/SlushUwU/PublicRiderPluginIssue

In this project the issue on line 16 look resolved I guess C# or the Template dont like minuses

**Comment by matkoch** [comment]
The template generates its own solution file. You've got another one. Therefore the run configurations aren't associated.

I'm not sure what error you mean in `TestEnvironment.cs`, but it sounds like you picked a name that has special symbols in it. Please use only pascal-case.

**Comment by SlushUwU** [comment]
> The template generates its own solution file. You've got another one. Therefore the run configurations aren't associated.
> 
> I'm not sure what error you mean in `TestEnvironment.cs`, but it sounds like you picked a name that has special symbols in it. Please use only pascal-case. 

How you mean it with "You've got another one?". And I know that the run configuration aren't associated, but I wonder why isn't it associated? I've downloaded the template

**Comment by matkoch** [comment]
In the repository, I see that you've got 2 solution files. Only the second will work, as it's part of the template.

![2023-10-17-Microsoft Edge-JetBrains-000465](https://github.com/JetBrains/resharper-rider-plugin/assets/5005566/0364d4cc-030d-4554-9b0a-1c88eb75f778)
