### ISSUE TITLE
Failed to start Visual Studio 2017

### ISSUE THREAD

**Issue by laurentkempe** [JetBrains/resharper-rider-plugin#9]
Using the script `.\runVisualStudio.ps1` I got a dialog showing the following error

> Invalid Command Line. Unknown Switch : ReSharper.Internal.

![image](https://user-images.githubusercontent.com/272612/52810837-d007ab00-3093-11e9-8f86-db806f7f98d6.png)

Here is the console log

	❯ .\runVisualStudio.ps1
	WARNING: Plugin is already installed. To trigger reinstall, delete C:\Users\laure\projects\Resharper\trial\Trial\src\dotnet\ReSharperPlugin.Trial\ReSharperPlugin.Trial.csproj.user.
	> C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\MSBuild.exe /t:Restore;Rebuild C:\Users\laure\projects\Resharper\trial\Trial\Trial.sln /v:minimal
	3996
	Microsoft (R) Build Engine version 16.0.360-preview+g9781d96883 for .NET Framework
	Copyright (C) Microsoft Corporation. All rights reserved.
	
	Restoring packages for C:\Users\laure\projects\Resharper\trial\Trial\src\dotnet\ReSharperPlugin.Trial\ReSharperPlugin.Trial.Rider.csproj...
	Restoring packages for C:\Users\laure\projects\Resharper\trial\Trial\src\dotnet\ReSharperPlugin.Trial\ReSharperPlugin.Trial.csproj...
	Restoring packages for C:\Users\laure\projects\Resharper\trial\Trial\src\dotnet\ReSharperPlugin.Trial.Tests\ReSharperPlugin.Trial.Tests.csproj...
	Installing JetBrains.Platform.UIInteractive.Text 183.0.20190208.91334.
	Installing JetBrains.Psi.Features.UIInteractive.Core 183.0.20190208.140150.
	Installing JetBrains.Platform.UIInteractive.Shell 183.0.20190208.91334.
	Installing JetBrains.Platform.UIInteractive.Ide 183.0.20190208.91334.
	Installing JetBrains.Platform.Core.MsBuild 183.0.20190208.91334.
	Installing JetBrains.Platform.Interop.dotMemoryUnit.Interop.Console 183.0.20190208.91334.
	Installing JetBrains.Platform.Core.Text 183.0.20190208.91334.
	Installing JetBrains.Psi.Features.UIInteractive.Features 183.0.20190208.140150.
	Installing JetBrains.Psi.Features.UIInteractive.SolutionAnalysis 183.0.20190208.140150.
	Installing JetBrains.Psi.Features.Diagramming 183.0.20190208.140150.
	Installing JetBrains.Platform.VisualStudio 183.0.20190208.91334.
	Installing JetBrains.Psi.Features.SolutionBuilder 183.0.20190208.140150.
	Installing JetBrains.Platform.RdProtocol 183.0.20190208.91334.
	Installing JetBrains.Platform.Core.Shell 183.0.20190208.91014.
	Installing JetBrains.Platform.Core.Ide 183.0.20190208.91334.
	Installing JetBrains.Platform.Interop.dotMemoryUnit.Interop.Ide 183.0.20190208.91334.
	Installing JetBrains.ReSharper.SDK.Tests 2018.3.3.
	Installing JetBrains.ReSharper.SDK.Internal 183.0.20190208.144139.
	Installing JetBrains.ReSharper.SDK 2018.3.3.
	Installing JetBrains.Psi.Features.Core 183.0.20190208.140150.
	Installing JetBrains.Psi.Features.test.Framework 183.0.20190208.140150.
	Installing JetBrains.Psi.Features.UnitTesting 183.0.20190208.140150.
	Installing JetBrains.Platform.Sdk 183.0.20190208.91334.
	Installing JetBrains.Platform.Tests.Framework 183.0.20190208.91334.
	Installing JetBrains.Psi.Features.src 183.0.20190208.140150.
	Installing JetBrains.Psi.Features.VisualStudio 183.0.20190208.140150.
	Installing JetBrains.ExternalAnnotations 10.2.55.
	Installing JetBrains.Psi.Features.Tasks 183.0.20190208.140150.
	Installing JetBrains.Platform.Interop.dotMemoryUnit.Framework 183.0.20190208.91334.
	Installing JetBrains.Platform.Interop.CommandLine 183.0.20190208.91334.
	Generating MSBuild file C:\Users\laure\projects\Resharper\trial\Trial\src\dotnet\ReSharperPlugin.Trial.Tests\obj\ReSharperPlugin.Trial.Tests\ReSharperPlugin.Trial.Tests.csproj.nuget.g.props.
	Generating MSBuild file C:\Users\laure\projects\Resharper\trial\Trial\src\dotnet\ReSharperPlugin.Trial\obj\ReSharperPlugin.Trial\ReSharperPlugin.Trial.csproj.nuget.g.props.
	Generating MSBuild file C:\Users\laure\projects\Resharper\trial\Trial\src\dotnet\ReSharperPlugin.Trial.Tests\obj\ReSharperPlugin.Trial.Tests\ReSharperPlugin.Trial.Tests.csproj.nuget.g.targets.
	Generating MSBuild file C:\Users\laure\projects\Resharper\trial\Trial\src\dotnet\ReSharperPlugin.Trial\obj\ReSharperPlugin.Trial\ReSharperPlugin.Trial.csproj.nuget.g.targets.
	Restore completed in 4.83 sec for C:\Users\laure\projects\Resharper\trial\Trial\src\dotnet\ReSharperPlugin.Trial.Tests\ReSharperPlugin.Trial.Tests.csproj.
	Restore completed in 4.82 sec for C:\Users\laure\projects\Resharper\trial\Trial\src\dotnet\ReSharperPlugin.Trial\ReSharperPlugin.Trial.csproj.
	Installing JetBrains.ReSharperAutomationTools.Native.Windows.Core 183.0.20190208.91332.
	Installing JetBrains.ReSharperAutomationTools.External.DebuggerLibs 183.0.20190208.141408.
	Installing JetBrains.ReSharperAutomationTools.src.CommandLineCore 183.0.20190208.141408.
	Installing JetBrains.Psi.Features.XamlRenderer 183.0.20190208.140150.
	Installing JetBrains.ReSharperAutomationTools.src.ReSharperHost 183.0.20190208.141408.
	Installing JetBrains.ReSharperAutomationTools.src.RiderSdk.Internal 183.0.20190208.141408.
	Installing JetBrains.Rider.SDK 2018.3.3.
	Generating MSBuild file C:\Users\laure\projects\Resharper\trial\Trial\src\dotnet\ReSharperPlugin.Trial\obj\ReSharperPlugin.Trial.Rider\ReSharperPlugin.Trial.Rider.csproj.nuget.g.props.
	Generating MSBuild file C:\Users\laure\projects\Resharper\trial\Trial\src\dotnet\ReSharperPlugin.Trial\obj\ReSharperPlugin.Trial.Rider\ReSharperPlugin.Trial.Rider.csproj.nuget.g.targets.
	Restore completed in 6.16 sec for C:\Users\laure\projects\Resharper\trial\Trial\src\dotnet\ReSharperPlugin.Trial\ReSharperPlugin.Trial.Rider.csproj.
	ReSharperPlugin.Trial -> C:\Users\laure\projects\Resharper\trial\Trial\src\dotnet\ReSharperPlugin.Trial\bin\ReSharperPlugin.Trial\Debug\ReSharperPlugin.Trial.dll
	InstallFolder: C:\Users\laure\AppData\Local\JetBrains\Installations\ReSharperPlatformVs15_59785107Trial
	ReSharperPlugin.Trial.Rider -> C:\Users\laure\projects\Resharper\trial\Trial\src\dotnet\ReSharperPlugin.Trial\bin\ReSharperPlugin.Trial.Rider\Debug\ReSharperPlugin.Trial.dll
	ReSharperPlugin.Trial.Tests -> C:\Users\laure\projects\Resharper\trial\Trial\src\dotnet\ReSharperPlugin.Trial.Tests\bin\ReSharperPlugin.Trial.Tests\Debug\ReSharperPlugin.Trial.Tests.dll
	> C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\devenv.exe /rootSuffix Trial /ReSharper.Internal
	3036

**Comment by laurentkempe** [comment]
Damn I just realized that it tries to start Visual Studio 2019 preview 2 in fact!

**Comment by matkoch** [comment]
So this is not an issue? It's because it wasn't available for 2019, right?

**Comment by laurentkempe** [comment]
I am not really sure, I have both Visual Studio 2017 and 2019 installed and both have R#, so how should the script behave?

**Comment by matkoch** [comment]
Can you delete the user file (second line from log) and paste the output from runVisualStudio.ps1 here again?

**Comment by laurentkempe** [comment]
@matkoch I created a new project which didn't have the file `\ReSharperPlugin.Trial.csproj.user.` and re-run `runVisualStudio.ps1`, see the log!
Then Visual Studio 2019 started with the same error dialog, and closed

    .\runVisualStudio.ps1
    Downloading from https://download.jetbrains.com/resharper/ReSharperUltimate.2018.3.3/JetBrains.ReSharperUltimate.2018.3.3.exe
    Installing experimental hive
    > C:\Users\laure\projects\Resharper\Trial\build\installer\JetBrains.ReSharperUltimate.2018.3.3.exe /VsVersion=15.0 /SpecificProductNames=ReSharper /Hive=Trial /Silent=True
    2564
    > C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\MSBuild.exe /t:Restore;Rebuild;Pack C:\Users\laure\projects\Resharper\Trial\Trial.sln /v:minimal /p:PackageVersion=1.0.0 /p:PackageOutputPath="C:\Users\laure\projects\Resharper\Trial\output"
    2064
    Microsoft (R) Build Engine version 16.0.360-preview+g9781d96883 for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.
    
      Persisting no-op dg to C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial\obj\ReSharperPlugin.Trial\ReSharperPlugin.Trial.csproj.nuget.dgspec.json
      Persisting no-op dg to C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial\obj\ReSharperPlugin.Trial.Rider\ReSharperPlugin.Trial.Rider.csproj.nuget.dgspec.json
      Persisting no-op dg to C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial.Tests\obj\ReSharperPlugin.Trial.Tests\ReSharperPlugin.Trial.Tests.csproj.nuget.dgspec.json
      Restore completed in 57.84 ms for C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial.Tests\ReSharperPlugin.Trial.Tests.csproj.
      Restore completed in 58.25 ms for C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial\ReSharperPlugin.Trial.csproj.
      Restore completed in 57.74 ms for C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial\ReSharperPlugin.Trial.Rider.csproj.
      ReSharperPlugin.Trial -> C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial\bin\ReSharperPlugin.Trial\Debug\ReSharperPlugin.Trial.dll
      ReSharperPlugin.Trial.Rider -> C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial\bin\ReSharperPlugin.Trial.Rider\Debug\ReSharperPlugin.Trial.dll
      ReSharperPlugin.Trial.Tests -> C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial.Tests\bin\ReSharperPlugin.Trial.Tests\Debug\ReSharperPlugin.Trial.Tests.dll
      Successfully created package 'C:\Users\laure\projects\Resharper\Trial\output\ReSharperPlugin.Trial.1.0.0.nupkg'.
    > C:\Users\laure\projects\Resharper\Trial\tools\nuget.exe install ReSharperPlugin.Trial -OutputDirectory C:\Users\laure\AppData\Local\JetBrains\plugins -Source C:\Users\laure\projects\Resharper\Trial\output -DependencyVersion Ignore
    3764
    Feeds used:
      C:\Users\laure\projects\Resharper\Trial\output
    
    Installing package 'ReSharperPlugin.Trial' to 'C:\Users\laure\AppData\Local\JetBrains\plugins'.
    Package "ReSharperPlugin.Trial.1.0.0" is already installed.
    Re-installing experimental hive
    > C:\Users\laure\projects\Resharper\Trial\build\installer\JetBrains.ReSharperUltimate.2018.3.3.exe /VsVersion=15.0 /SpecificProductNames=ReSharper /Hive=Trial /Silent=True
    3776
    > C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\MSBuild.exe /t:Restore;Rebuild C:\Users\laure\projects\Resharper\Trial\Trial.sln /v:minimal
    1828
    Microsoft (R) Build Engine version 16.0.360-preview+g9781d96883 for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.
    
      Persisting no-op dg to C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial\obj\ReSharperPlugin.Trial\ReSharperPlugin.Trial.csproj.nuget.dgspec.json
      Persisting no-op dg to C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial\obj\ReSharperPlugin.Trial.Rider\ReSharperPlugin.Trial.Rider.csproj.nuget.dgspec.json
      Persisting no-op dg to C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial.Tests\obj\ReSharperPlugin.Trial.Tests\ReSharperPlugin.Trial.Tests.csproj.nuget.dgspec.json
      Restore completed in 550.4 ms for C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial.Tests\ReSharperPlugin.Trial.Tests.csproj.
      Restore completed in 550.47 ms for C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial\ReSharperPlugin.Trial.Rider.csproj.
      Restore completed in 551.14 ms for C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial\ReSharperPlugin.Trial.csproj.
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3101: Could not write state file "obj\ReSharperPlugin.Trial\Debug\ReSharperPlugin.T rial.csprojAssemblyReference.cache". The process cannot access the file 'C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial\obj\ReSharperPlugin.Trial\Debug\ReSharperPlugin.Trial.csprojAssemblyReference .cache' because it is being used by another process. [C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial\ReSharperPlugin.Trial.csproj]
      ReSharperPlugin.Trial -> C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial\bin\ReSharperPlugin.Trial\Debug\ReSharperPlugin.Trial.dll
      InstallFolder: C:\Users\laure\AppData\Local\JetBrains\Installations\ReSharperPlatformVs15_59785107Trial
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3088: Could not read state file "obj\ReSharperPlugin.Trial.Rider\Debug\ReSharperPlu gin.Trial.Rider.csprojAssemblyReference.cache". The process cannot access the file 'C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial\obj\ReSharperPlugin.Trial.Rider\Debug\ReSharperPlugin.Trial.Rider. csprojAssemblyReference.cache' because it is being used by another process. [C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial\ReSharperPlugin.Trial.Rider.csproj]
      ReSharperPlugin.Trial.Rider -> C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial\bin\ReSharperPlugin.Trial.Rider\Debug\ReSharperPlugin.Trial.dll
      ReSharperPlugin.Trial.Tests -> C:\Users\laure\projects\Resharper\Trial\src\dotnet\ReSharperPlugin.Trial.Tests\bin\ReSharperPlugin.Trial.Tests\Debug\ReSharperPlugin.Trial.Tests.dll
    > C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\devenv.exe /rootSuffix Trial /ReSharper.Internal

**Comment by matkoch** [comment]
Please try changing this line https://github.com/JetBrains/resharper-rider-plugin/blob/master/content/runVisualStudio.ps1#L30

I will introduce a parameter for this.

**Comment by laurentkempe** [comment]
Sorry you want me to change that line to what?

**Comment by matkoch** [comment]
VisualStudio 2019 is `v16.0`

**Comment by laurentkempe** [comment]
🤣 oh sure! LOL
I also changed https://github.com/JetBrains/resharper-rider-plugin/blob/master/content/runVisualStudio.ps1#L58

But now I get that

    .\runVisualStudio.ps1
    Using JetBrains.ReSharperUltimate.2018.3.3.exe from cache
    Installing experimental hive
    > C:\Users\laure\projects\Resharper\Trial\build\installer\JetBrains.ReSharperUltimate.2018.3.3.exe /VsVersion=16.0 /SpecificProductNames=ReSharper /Hive=Trial /Silent=True
    3492
    Exception calling "Save" with "1" argument(s): "The given path's format is not supported."
    At C:\Users\laure\projects\Resharper\Trial\runVisualStudio.ps1:52 char:9
    +         $PackagesXml.Save("$InstallationDirectory\packages.config")
    +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        + FullyQualifiedErrorId : DotNetMethodException

**Comment by matkoch** [comment]
Can you check please what's inside $InstallationDirectory?

**Comment by laurentkempe** [comment]
> Can you check please what's inside $InstallationDirectory?

    C:\Users\laure\AppData\Roaming\JetBrains\ReSharperPlatformVs15\v183_59785107Trial

**Comment by matkoch** [comment]
Should be fixed in 0.9.0

**Comment by laurentkempe** [comment]
Works like a charm now! 🚀 👍 
![image](https://user-images.githubusercontent.com/272612/55032692-c3bb2a00-5011-11e9-8950-756d66aba0f1.png)
